service: wiseape-desktop
runtime: nodejs16
env: standard
env_variables:
  DBHOST: "34.67.143.103"
  DBNAME: "wiseape-client"
  DBUSER: "nodeuser"
  DBPASSWORD: "RotiKeju98*"
  DBENGINE: "postgresql"
  APPLICATION_NAME : "Wiseape Desktop"
  APPLICATION_TITLE : "Wiseape Desktop"
  APPLICATION_PORT : "8080"
  PROJECT : "huda-playground"

