service: wiseape-desktop
runtime: nodejs16
env: standard
env_variables:
  DBHOST: "34.67.143.103"
  DBNAME: "wiseape-client"
  DBUSER: "<dbuser>"
  DBPASSWORD: "<dbpassword>"
  DBENGINE: "postgresql"
  APPLICATION_NAME : "<appname>"
  APPLICATION_TITLE : "<apptitle>"
  APPLICATION_PORT : "8080"
  PROJECT : "huda-playground"

